apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: LoginApplication
spec:
  selector:
    matchLabels:
      app: LoginApplication
      tier: web
  template:
    metadata:
      labels:
        app: LoginApplication
        tier: web
    spec:
      containers:
      - name: login-application
        image: us.gcr.io/gcp-docker-kubernetes-960826/spring-login:0.1.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spring-login-config
