apiVersion: v1
kind: Service
metadata:
  name: spring-chat-service
  labels:
    app: ChatApplication
spec:
  selector:
    app: ChatApplication
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
