apiVersion: v1
kind: Service
metadata:
  name: spring-profile-service
  labels:
    app: ProfileApplication
spec:
  selector:
    app: ProfileApplication
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
